Config = {}
Config.UseTruckerJob = false -- true = The shops stock is based on when truckers refill it | false = shop inventory never runs out
Config.UseTarget = GetConvar('UseTarget', 'false') == 'true' -- Use qb-target interactions (don't change this, go to your server.cfg and add `setr UseTarget true` to use this and just that from true to false or the other way around)
Config.FirearmsLicenseCheck = true -- Whether a arms dealer checks for a firearms license
Config.ShopsInvJsonFile = './json/shops-inventory.json' -- json file location
Config.SellCasinoChips = {
    coords = vector4(988.6, 29.73, 71.47, 35.64),
    radius = 1.5,
    ped = 's_m_y_casino_01'
}
Config.Products = {
    ["normal"] = {
        [1] = {
            name = "water_bottle",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "kurkakola",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "twerks_candy",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "snikkel_candy",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "lighter",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "redw",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = 'boosterpack',
            price = 1000,
            amount = 50,
            info = {},
            type = 'item',
            slot = 7,
        },
        [8] = {
            name = "scratch_ticket",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
    },
    ["liquor"] = {
        [1] = {
            name = "beer",
            price = 7,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "whiskey",
            price = 10,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "vodka",
            price = 12,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
    },
    ["hardware"] = {
        [1] = {
            name = "lockpick",
            price = 150,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_wrench",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weapon_hammer",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "weapon_crowbar",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "screwdriverset",
            price = 1000,
            amount = 20,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "repairkit",
            price = 1500,
            amount = 10,
            info = {},
            type = "item",
            slot = 6,
        }, 
        [7] = {
            name = "gastube",
            price = 12,
            amount = 1000,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "spray",
            price = 500,
            amount = 5,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "kq_outfitbag",
            price = 8000,
            amount = 5,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "rag",
            price = 100,
            amount = 5,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "spray_remover",
            price = 100,
            amount = 75,
            info = {},
            type = "item",
            slot = 11,
        },
    },
    ["hardware2"] = {
        [1] = {
            name = "robbery_grinder",
            price = 2500,
            amount = 5,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "cutter",
            price = 8000,
            amount = 5,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "bolt_cutter",
            price = 5000,
            amount = 5,
            info = {},
            type = "item",
            slot = 3,
        },   
        [4] = {
            name = "welding-tool",
            price = 5000,
            amount = 5,
            info = {},
            type = "item",
            slot = 4,
        },    
        [5] = {
            name = "goldpan",
            price = 7500,
            amount = 5,
            info = {},
            type = "item",
            slot = 5,
        },  
        [6] = {
            name = "pickaxe",
            price = 350,
            amount = 5,
            info = {},
            type = "item",
            slot = 6,
        }, 
        [7] = {
            name = "shovel",
            price = 550,
            amount = 5,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "drill",
            price = 6500,
            amount = 5,
            info = {},
            type = "item",
            slot = 8,
        }, 
        [9] = {
            name = "miningdrill",
            price = 25000,
            amount = 5,
            info = {},
            type = "item",
            slot = 9,
        }, 
        [10] = {
            name = "mininglaser",
            price = 35000,
            amount = 5,
            info = {},
            type = "item",
            slot = 10,
        }, 
        [11] = {
            name = "drillbit",
            price = 2000,
            amount = 5,
            info = {},
            type = "item",
            slot = 11,
        }, 
        [12] = {
            name = "powersaw",
            price = 2000,
            amount = 5,
            info = {},
            type = "item",
            slot = 12,
        }, 
    },
    ["weedshop"] = {
        [1] = {
            name = "lighter",
            price = 35,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "vape",
            price = 1500,
            amount = 10,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "empty_weed_bag",
            price = 2,
            amount = 1000,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "rolling_paper",
            price = 5,
            amount = 100,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "liquid",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        }, 
    },
    ["leisureshop"] = {
        [1] = {
            name = "skateboard",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "parachute",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "binoculars",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "diving_gear",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "diving_fill",
            price = 500,
            amount = 10,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "weapon_bat",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "metaldetector", 
            price = 3500, 
            amount = 50, 
            info = {}, 
            type = "item", 
            slot = 7,
          },
        [8] = {
            name = "sharkrepelent", 
            price = 1500, 
            amount = 10, 
            info = {}, 
            type = "item", 
            slot = 8,
        },
        [9] = {
            name = "yogamat_black", 
            price = 750, 
            amount = 10, 
            info = {}, 
            type = "item", 
            slot = 9,
        },
        [10] = {
            name = "yogamat_blue", 
            price = 750, 
            amount = 10, 
            info = {}, 
            type = "item", 
            slot = 10,
        },
        [11] = {
            name = "yogamat_red", 
            price = 750, 
            amount = 10, 
            info = {}, 
            type = "item", 
            slot = 11,
        },
        [12] = {
            name = "yogamat_pro", 
            price = 750, 
            amount = 10, 
            info = {}, 
            type = "item", 
            slot = 12,
        },
    },
    ["weapons"] = {
        [1] = {
            name = "weapon_knife",
            price = 2500,
            amount = 250,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_bat",
            price = 2500,
            amount = 250,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weapon_hatchet",
            price = 2500,
            amount = 250,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "pistol_ammo",
            price = 450,
            amount = 100,
            info = {},
            type = "item",
            slot = 5,
        },
        [5] = {
            name = "weapon_vintagepistol",
            price = 6500,
            amount = 5,
            info = {},
            type = "item",
            slot = 6,
            requiresLicense = true
        },
        [6] = {
            name = "weapon_pistol",
            price = 8500,
            amount = 5,
            info = {},
            type = "item",
            slot = 7,
            requiresLicense = true
        },
        [7] = {
            name = "weapon_snspistol",
            price = 7500,
            amount = 5,
            info = {},
            type = "item",
            slot = 8,
            requiresLicense = true
        },
        [8] = {
            name = "weapon_revolver",
            price = 8500,
            amount = 5,
            info = {},
            type = "item",
            slot = 9,
            requiresLicense = true
        },
        [9] = {
            name = "weapon_snspistol_mk2",
            price = 8000,
            amount = 5,
            info = {},
            type = "item",
            slot = 10,
            requiresLicense = true
        },
    },
    ["pokemon"] = {
        [1] = {
            name = 'boosterpack',
            price = 1000,
            amount = 50,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'boosterbox',
            price = 3500,
            amount = 10,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'pokebox',
            price = 6500,
            amount = 50,
            info = {},
            type = 'item',
            slot = 3,
        }
    },
    ["huntstore"] = {
        [1] = {
            name = 'pickaxe',
            price = 850,
            amount = 50,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'camp',
            price = 350,
            amount = 50,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'binoculars',
            price = 2500,
            amount = 50,
            info = {},
            type = 'weapon',
            slot = 3,
        },
        [4] = {
            name = "metaldetector", 
            price = 3500, 
            amount = 50, 
            info = {}, 
            type = "item", 
            slot = 4,
          },
        [5] = {
            name = "parachute",
            price = 5000,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "weapon_knife",
            price = 1250,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = 'weapon_musket',
            price = 7500,
            amount = 10,
            info = {},
            type = 'item',
            slot = 7,
            requiresLicense = true
        },
    },
    ["pooldrinks"] = {
        [1] = {
            name = 'beer',
            price = 75,
            amount = 50,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'whiskey',
            price = 75,
            amount = 50,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'vodka',
            price = 75,
            amount = 50,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'water_bottle',
            price = 59,
            amount = 50,
            info = {},
            type = 'item',
            slot = 4,
        },
        [5] = {
            name = 'twerks_candy',
            price = 59,
            amount = 50,
            info = {},
            type = 'item',
            slot = 5,
        },
    },
    ["poolhall"] = {
        [1] = {
            name = "weapon_poolcue",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
    },
    ["bait"] = {
        [1] = {
            name = 'fishingbait',
            price = 10,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'fishinglure',
            price = 250,
            amount = 10,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'fishinglure2',
            price = 500,
            amount = 10,
            info = {},
            type = 'item',
            slot = 3,
        },
    },
    ["golfrental"] = {
        [1] = {
            name = "weapon_golfclub",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
    },
    ["fishstore"] = {
        [1] = {
            name = 'fishingrod',
            price = 500,
            amount = 10,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'fishingrod2',
            price = 1000,
            amount = 10,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'fishingrod3',
            price = 1500,
            amount = 10,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'fishinglure',
            price = 250,
            amount = 10,
            info = {},
            type = 'item',
            slot = 4,
        },
        [5] = {
            name = 'fishinglure2',
            price = 500,
            amount = 10,
            info = {},
            type = 'item',
            slot = 5,
        },
        [6] = {
            name = 'skill-reel',
            price = 2500,
            amount = 10,
            info = {},
            type = 'item',
            slot = 6,
        },
        [7] = {
            name = 'pro-reel',
            price = 3500,
            amount = 10,
            info = {},
            type = 'item',
            slot = 7,
        },
        [8] = {
            name = 'fishingbait',
            price = 10,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 8,
        },
        [9] = {
            name = "sharkrepelent", 
            price = 1500, 
            amount = 10, 
            info = {}, 
            type = "item", 
            slot = 9,
          },
    },
    ["blackmarket"] = {
        [1] = {
            name = 'greenchip',
            price = 3500,
            amount = 5,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'tablet',
            price = 5,
            amount = 8000,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'burnerphone',
            price = 6500,
            amount = 5,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'boostingtablet',
            price = 15000,
            amount = 5,
            info = {},
            type = 'item',
            slot = 4,
        },
        [5] = {
            name = 'bleach',
            price = 750,
            amount = 5,
            info = {},
            type = 'item',
            slot = 5,
        },
        [6] = {
            name = 'microfibrecloth',
            price = 125,
            amount = 5,
            info = {},
            type = 'item',
            slot = 6,
        },
        [7] = { 
            name = 'deliverylist',
            price = 350,
            amount = 5,
            info = {},
            type = 'item',
            slot = 7,
        },
        [8] = { 
            name = 'basicdecrypter',
            price = 1250,
            amount = 5,
            info = {},
            type = 'item',
            slot = 8,
    },
    },
    ["illegalpharmacy"] = {
        [1] = {
            name = 'methlab',
            price = 7000,
            amount = 5,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'morphine',
            price = 10,
            amount = 100,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'lsd_paper',
            price = 5,
            amount = 100,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'levamisole',
            price = 5,
            amount = 1000,
            info = {},
            type = 'item',
            slot = 4,
        },
    },
    ["phoneshop"] = {
        [1] = {
            name = "classic_phone",
            price = 800,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "black_phone",
            price = 1200,
            amount = 10,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "blue_phone",
            price = 1200,
            amount = 10,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "red_phone",
            price = 1200,
            amount = 10,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "green_phone", 
            price = 1200,
            amount = 10,
            info = {}, 
            type = "item", 
            slot = 5,
          },
        [6] = {
            name = "greenlight_phone", 
            price = 1200,
            amount = 10,
            info = {}, 
            type = "item", 
            slot = 6,
          },
        [7] = {
            name = "pink_phone", 
            price = 1200,
            amount = 10,
            info = {}, 
            type = "item", 
            slot = 7,
          },
        [8] = {
            name = "white_phone", 
            price = 1200,
            amount = 10,
            info = {}, 
            type = "item", 
            slot = 8,
          },
          [9] = {
            name = "gold_phone", 
            price = 25000,
            amount = 10,
            info = {}, 
            type = "item", 
            slot = 9,
          },
    },
    ["digitalstore"] = {
        [1] = {
            name = "vpn",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "radio",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "radiocar", 
            price = 12500, 
            amount = 5, 
            info = {}, 
            type = "item", 
            slot = 3,
          },
          [4] = {
            name = "racingtablet", 
            price = 15000, 
            amount = 5, 
            info = {}, 
            type = "item", 
            slot = 4,
          },
          [5] = {
            name = "lithium", 
            price = 8, 
            amount = 50, 
            info = {}, 
            type = "item", 
            slot = 5,
          },
          [6] = { 
            name = "powerbank", 
            price = 850, 
            amount = 5, 
            info = {}, 
            type = "item", 
            slot = 6,
          },
          [7] = { 
            name = "laptop_green", 
            price = 2000, 
            amount = 5, 
            info = {}, 
            type = "item", 
            slot = 7,
        },
    },
    ["pharmacy"] = {
        [1] = {
            name = 'bandage',
            price = 500,
            amount = 10,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'painkillers',
            price = 750,
            amount = 10,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'adderall',
            price = 10,
            amount = 50,
            info = {},
            type = 'item',
            slot = 3,
        },
    },
   --[[  ["casino"] = {
        [1] = {
            name = 'casinochips',
            price = 1,
            amount = 250000,
            info = {},
            type = 'item',
            slot = 1,
        }
    }, ]]
} 
Config.Locations = {

    -- // Custom SHops \\ --

    ["247supermarket11"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(377.63, -1787.13, 29.52, 322.99),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(386.46, -1779.13, 29.55, 129.41)
    },

    -- 24/7 Locations
    ["247supermarket"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(24.47, -1346.62, 29.5, 271.66),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(26.45, -1315.51, 29.62, 0.07)
    },

    ["247supermarket2"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-3039.54, 584.38, 7.91, 17.27),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-3047.95, 590.71, 7.62, 19.53)
    },

    ["247supermarket3"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-3242.97, 1000.01, 12.83, 357.57),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-3245.76, 1005.25, 12.83, 269.45)
    },

    ["247supermarket4"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1728.07, 6415.63, 35.04, 242.95),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1741.76, 6419.61, 35.04, 6.83)
    },

    ["247supermarket5"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1959.82, 3740.48, 32.34, 301.57),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1963.81, 3750.09, 32.26, 302.46)
    },

    ["247supermarket6"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(549.13, 2670.85, 42.16, 99.39),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(541.54, 2663.53, 42.17, 120.51)
    },

    ["247supermarket7"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(2677.47, 3279.76, 55.24, 335.08),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(2662.19, 3264.95, 55.24, 168.55)
    },

    ["247supermarket8"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(2556.66, 380.84, 108.62, 356.67),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(2553.24, 399.73, 108.56, 344.86)
    },

    ["247supermarket9"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(372.66, 326.98, 103.57, 253.73),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(379.97, 357.3, 102.56, 26.42)
    },

    ["247supermarket10"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(161.75, 6642.27, 31.7, 227.92),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(379.97, 357.3, 102.56, 26.42)
    },

    -- LTD Gasoline Locations
    ["ltdgasoline"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-47.02, -1758.23, 29.42, 45.05),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-40.51, -1747.45, 29.29, 326.39)
    },

    ["ltdgasoline2"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-706.06, -913.97, 19.22, 88.04),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-702.89, -917.44, 19.21, 181.96)
    },

    ["ltdgasoline3"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-1820.02, 794.03, 138.09, 135.45),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1829.29, 801.49, 138.41, 41.39)
    },

    ["ltdgasoline4"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(1164.71, -322.94, 69.21, 101.72),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1160.62, -312.06, 69.28, 3.77)
    },

    ["ltdgasoline5"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(1697.87, 4922.96, 42.06, 324.71),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1702.68, 4917.28, 42.22, 139.27)
    },

    ["ltdgasoline6"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(294.3, -1259.83, 29.45, 183.63),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(379.97, 357.3, 102.56, 26.42)
    },

    ["ltdgasoline7"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-2067.49, -320.79, 13.32, 174.62),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(379.97, 357.3, 102.56, 26.42)
    },

    ["ltdgasoline8"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-527.04, -1228.48, 18.44, 63.86),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(379.97, 357.3, 102.56, 26.42)
    },


    -- Rob's Liquor Locations
    ["robsliquor"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-1221.58, -908.15, 12.33, 35.49),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1226.92, -901.82, 12.28, 213.26)
    },

    ["robsliquor2"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-1486.59, -377.68, 40.16, 139.51),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1468.29, -387.61, 38.79, 220.13)
    },

    ["robsliquor3"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-2966.39, 391.42, 15.04, 87.48),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-2961.49, 376.25, 15.02, 111.41)
    },

    ["robsliquor4"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(1165.17, 2710.88, 38.16, 179.43),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1194.52, 2722.21, 38.62, 9.37)
    },

    ["robsliquor5"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(1134.2, -982.91, 46.42, 277.24),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1129.73, -989.27, 45.97, 280.98)
    },

    ["robsliquor6"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-161.11, 6321.42, 31.59, 318.34),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1129.73, -989.27, 45.97, 280.98)
    },

    -- Hardware Store Locations
    ["hardware"] = {
        ["label"] = "General Store",
        ["coords"] = vector4(245.15, -266.04, 54.04, 337.91),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Open General Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = false,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(89.15, -1745.29, 30.09, 315.25)
    },

    -- // Highway You Tool
    ["hardware2"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(2737.82, 3461.86, 55.7, 333.48),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Open Hardware Store",
        ["products"] = Config.Products["hardware2"],
        ["showblip"] = false,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(2704.68, 3457.21, 55.54, 176.28)
    },

    -- Ammunation Locations
    ["ammunation"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-659.1, -939.75, 21.83, 95.11),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = false,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-660.61, -938.14, 21.83, 167.22)
    },
    ["ammunation2"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(813.37, -2155.24, 29.62, 358.99),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = false,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(820.97, -2146.7, 28.71, 359.98)
    },
    ["ammunation3"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(1697.78, 3757.58, 34.71, 134.2),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = false,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1687.17, 3755.47, 34.34, 163.69)
    },
    ["ammunation4"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-326.28, 6081.43, 31.45, 132.13),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = false,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-341.72, 6098.49, 31.32, 11.05)
    },
    ["ammunation5"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(246.95, -51.41, 69.94, 341.61),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = false,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(249.0, -50.64, 69.94, 60.71)
    },
    ["ammunation6"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(18.38, -1108.0, 29.8, 160.15),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = false,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-5.82, -1107.48, 29.0, 164.32)
    },
    ["ammunation7"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(2564.75, 298.84, 108.73, 260.36),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = false,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(2578.77, 285.53, 108.61, 277.2)
    },
    ["ammunation8"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-1112.53, 2697.35, 18.55, 139.66),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = false,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1127.67, 2708.18, 18.8, 41.76)
    },
    ["ammunation9"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(841.19, -1028.95, 28.19, 272.48),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = false,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(847.83, -1020.36, 27.88, 88.29)
    },
    ["ammunation10"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-1310.66, -394.4, 36.7, 345.81),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = false,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1302.44, -385.23, 36.62, 303.79)
    },
    ["ammunation11"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-3167.2, 1087.02, 20.84, 155.38),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = false,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-3183.6, 1084.35, 20.84, 68.13)
    },

    ["ammunation12"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(1255.16, 2713.25, 38.13, 177.1),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = false,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-3183.6, 1084.35, 20.84, 68.13)
    },

--[[     -- Casino Locations
    ["casino"] = {
        ["label"] = "Diamond Casino",
        ["coords"] = vector4(988.88, 33.13, 71.47, 306.3),
        ["ped"] = 'csb_tomcasino',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-coins",
        ["targetLabel"] = "Buy Casino Chips",
        ["products"] = Config.Products["casino"],
        ["showblip"] = false,
        ["blipsprite"] = 617,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(972.6, 9.22, 81.04, 233.38)
    }, ]]

--[[     ["casinobar"] = {
        ["label"] = "Casino Bar",
        ["coords"] = vector4(978.11, 25.12, 71.46, 33.74),
        ["ped"] = 'a_m_y_smartcaspat_01',
        ["scenario"] = "WORLD_HUMAN_VALET",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Talk to Casino Bartender",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(937.16, 1.0, 78.76, 152.4)
    },
 ]]

    -- //// CUSTOM SHOPS \\\\ --

        -- Leisure Shop Locations
    ["leisureshop"] = {
        ["label"] = "Leisure Shop",
        ["coords"] = vector4(-1127.28, -1439.41, 5.23, 302.93),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["leisureshop"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1507.64, 1505.52, 115.29, 262.2)
    },
    
     -- Pokemon Store
    ["pokemonstore"] = {
        ["label"] = "Pokemon Shop",
        ["coords"] = vector4(388.36, -760.58, 29.65, 96.32),
        ["ped"] = 'u_m_y_imporage',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Pokemon Shop",
        ["products"] = Config.Products["pokemon"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1507.64, 1505.52, 115.29, 262.2)
    },

    -- Weed Shop
    ["weedshop"] = {
        ["label"] = "White Widow",
        ["coords"] = vector4(188.04, -241.76, 54.07, 251.95),
        ["ped"] = 's_m_o_busker_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Talked to stoned guy",
        ["products"] = Config.Products["weedshop"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1507.64, 1505.52, 115.29, 262.2)
    },

    -- Hunting Shop
    ["huntstore"] = {
        ["label"] = "Hunting Store",
        ["coords"] = vector4(-775.7, 5604.21, 33.74, 252.62),
        ["ped"] = 's_m_m_cntrybar_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Hunting Store",
        ["products"] = Config.Products["huntstore"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1507.64, 1505.52, 115.29, 262.2)
    },

    -- Pool Hall Drinks
    ["pooldrinks"] = {
        ["label"] = "Pool Hall Drinks",
        ["coords"] = vector4(-1584.3, -992.49, 13.08, 47.21),
        ["ped"] = 's_f_y_clubbar_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Talk to bartender",
        ["products"] = Config.Products["pooldrinks"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1507.64, 1505.52, 115.29, 262.2)
    },
    -- Pool Hall
    ["poolhall"] = {
        ["label"] = "Pool Hall",
        ["coords"] = vector4(-1582.31, -987.0, 13.08, 79.95),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Poolhall Shop",
        ["products"] = Config.Products["poolhall"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1507.64, 1505.52, 115.29, 262.2)
    },

     -- Bait Guy
    ["baitguy"] = {
        ["label"] = "Fisherman",
        ["coords"] = vector4(-1877.09, -1215.42, 13.02, 143.37),
        ["ped"] = 'a_m_m_polynesian_01',
        ["scenario"] = "WORLD_HUMAN_STAND_FISHING",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Talk to Fisherman",
        ["products"] = Config.Products["bait"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1507.64, 1505.52, 115.29, 262.2)
    },

    -- Golf Guy
    ["golfrental"] = {
        ["label"] = "Golf Shop",
        ["coords"] = vector4(-1733.28, -1133.99, 13.07, 144.59),
        ["ped"] = 'a_m_m_golfer_01',
        ["scenario"] = "WORLD_HUMAN_GOLF_PLAYER",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Golf Shop",
        ["products"] = Config.Products["golfrental"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1507.64, 1505.52, 115.29, 262.2)
    },

    -- Fishing Shop
    ["fishstore"] = {
        ["label"] = "Fishing Shop",
        ["coords"] = vector4(-1593.32, 5197.15, 4.36, 17.1),
        ["ped"] = 'a_m_m_hillbilly_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Fishing Shop",
        ["products"] = Config.Products["fishstore"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1507.64, 1505.52, 115.29, 262.2)
    },

    -- Digital Den
    ["digitalstore"] = {
        ["label"] = "Digital Store",
        ["coords"] = vector4(-627.54, -275.08, 35.58, 116.67),
        ["ped"] = 'a_f_m_business_02',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Digital Store",
        ["products"] = Config.Products["digitalstore"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1507.64, 1505.52, 115.29, 262.2)
    },

    -- Phone Shop
    ["phoneshop"] = {
        ["label"] = "Phone Shop",
        ["coords"] = vector4(-777.17, -618.37, 30.28, 4.69),
        ["ped"] = 'u_m_y_baygor',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Phone Store",
        ["products"] = Config.Products["phoneshop"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1507.64, 1505.52, 115.29, 262.2)
    },

        -- Pharmacy
        ["pharmacy"] = {
            ["label"] = "Pharmacy",
            ["coords"] = vector4(1741.88, 3639.05, 34.85, 116.58),
            ["ped"] = 's_m_m_scientist_01',
            ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
            ["radius"] = 1.5,
            ["targetIcon"] = "fas fa-leaf",
            ["targetLabel"] = "Talk to Pharmacist",
            ["products"] = Config.Products["pharmacy"],
            ["showblip"] = false,
            ["blipsprite"] = 52,
            ["blipscale"] = 0.8,
            ["blipcolor"] = 0,
            ["delivery"] = vector4(-1507.64, 1505.52, 115.29, 262.2)
        },

        -- Blackmarket
        ["blackmarket"] = {
            ["label"] = "Black Market",
            ["coords"] = vector4(2917.07, 4629.57, 49.2, 229.7) ,
            ["ped"] = 'a_m_y_salton_01',
            ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
            ["radius"] = 1.5,
            ["targetIcon"] = "fas fa-leaf",
            ["targetLabel"] = "Talk to Shady Dealer",
            ["products"] = Config.Products["blackmarket"],
            ["showblip"] = false,
            ["blipsprite"] = 52,
            ["blipscale"] = 0.8,
            ["blipcolor"] = 0,
            ["delivery"] = vector4(-1507.64, 1505.52, 115.29, 262.2)
        },

            -- Illegal Pharmacy
            ["illegalpharmacy"] = {
                ["label"] = "Pharmacy",
                ["coords"] = vector4(1422.89, 6330.15, 24.69, 34.14),
                ["ped"] = 's_m_m_scientist_01',
                ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
                ["radius"] = 1.5,
                ["targetIcon"] = "fas fa-leaf",
                ["targetLabel"] = "Talk to Shady Pharmacist",
                ["products"] = Config.Products["illegalpharmacy"],
                ["showblip"] = false,
                ["blipsprite"] = 52,
                ["blipscale"] = 0.8,
                ["blipcolor"] = 0,
                ["delivery"] = vector4(-1507.64, 1505.52, 115.29, 262.2)
            },

}   
