Config = {
    debug = false, -- Define if you want to see the debug messages [true, false]
    locale = 'en', -- Translate the script into your selected language, can be en, fr, etc (English, French, etc). If you wan't make your own traduction, add a new file in Locales folder and copy the en.json and name it 'YOUR_LANG_FILE.json' file to use it as base.

    chinUpPlayCost = 5, -- Define the cost of the chin up challenge [number]
    chinUpReward = 100, -- Define the price of the win [number]
    chinUpRetyTime = 30, -- Define the retry time of the chin up challenge if the player win [minutes]

    -- Define the placement of each game do not change unless you know what you are doing.
    placements = {
        -- Beach Placement
        {
            games = {
                {
                    name = 'patoche_gamestand_prop_gym_01',
                    position = vec3(-1564.89282, -1035.64136, 12.0284033),
                    rotation = vec3(0.0, 0.0, 50.0),
                    difficulty = {
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'medium',
                        'medium',
                        'medium',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'hard',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'medium',
                        'medium',
                        'hard',
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'hard',
                        'medium',
                        'easy',
                        'hard',
                        'hard',
                    },
                    distance = 2.0,
                    duration = 60
                },

                {
                    name = 'patoche_gamestand_prop_gym_01',
                    position = vec3(-1567.02893, -1038.03, 12.0235081),
                    rotation = vec3(0.0, 0.0, 50.0),
                    difficulty = {
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'medium',
                        'medium',
                        'medium',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'hard',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'medium',
                        'medium',
                        'hard',
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'hard',
                        'medium',
                        'easy',
                        'hard',
                        'hard',
                    },
                    distance = 2.0,
                    duration = 60
                },

                {
                    name = "patoche_gamestand_01",
                    position = vec3(-1571.23865, -1042.54541, 12.5976734),
                    rotation = vec3(-0.0, -0.0, -130.0),
                    distance = 3.0,
                    duration = 60,
                    weapon = "WEAPON_AIRRIFLE",
                    ammo = 30
                },

                {
                    name = "patoche_gamestand_01",
                    position = vec3(-1543.08142, -990.368469, 12.6042271),
                    rotation = vec3(0.0, 0.0, 50.0),
                    distance = 3.0,
                    duration = 60,
                    weapon = "WEAPON_AIRRIFLE",
                    ammo = 30
                },

                {
                    name = "patoche_gamestand_02",
                    position = vec3(-1559.15369, -1029.51221, 12.5279036),
                    rotation = vec3(-0.0, 0.0, 50.0),
                    distance = 3.0,
                    duration = 60,
                    weapon = "WEAPON_AIRRIFLE",
                    ammo = 30
                },

                {
                    name = "patoche_gamestand_02",
                    position = vec3(-1560.47681, -1009.13629, 12.5279036),
                    rotation = vec3(-0.0, -0.0, -130.0),
                    distance = 3.0,
                    duration = 60,
                    weapon = "WEAPON_AIRRIFLE",
                    ammo = 30
                },

                {
                    name = "patoche_gamestand_03",
                    position = vec3(-1552.43237, -1021.89838, 12.0163116),
                    rotation = vec3(-0.0, -0.0, -130.0),
                    distance = 4.0,
                    duration = 40,
                    weapon = "WEAPON_TWBALL",
                    ammo = 10
                },

                {
                    name = "patoche_gamestand_trampo",
                    position = vec3(-1545.650, -1012.664, 13.888),
                    rotation = vec3(0.0, 0.0, 0.0),
                    distance = 4.0,
                    duration = 10
                }
            }
        },
        -- Paleto Placement
        {
            games = {
                {
                    name = 'patoche_gamestand_prop_gym_01',
                    position = vec3(144.259354, 6431.04834, 30.360611),
                    rotation = vec3(0.0, 0.0, -144.0),
                    difficulty = {
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'medium',
                        'medium',
                        'medium',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'hard',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'medium',
                        'medium',
                        'hard',
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'hard',
                        'medium',
                        'easy',
                        'hard',
                        'hard',
                    },
                    distance = 2.0,
                    duration = 60
                },

                {
                    name = 'patoche_gamestand_prop_gym_01',
                    position = vec3(115.739914, 6445.67773, 30.8137283),
                    rotation = vec3(0.0, 0.0, -136.0),
                    difficulty = {
                        'easy',
                        'easy',
                        'medium',
                        'medium',
                        'hard',
                        'hard',
                        'easy',
                        'easy',
                        'easy',
                        { areaSize = 30, speedMultiplier = 1.5 },
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'medium',
                        'hard',
                        'medium',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'hard',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'medium',
                        'medium',
                        'hard',
                        'easy',
                        'medium',
                        'easy',
                        'hard',
                        'easy',
                        'hard',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'hard',
                        'medium',
                        'easy',
                        'hard',
                        'hard',
                    },
                    distance = 2.0,
                    duration = 60
                },

                {
                    name = "patoche_gamestand_01",
                    position = vec3(132.2851, 6431.146, 30.9643517),
                    rotation = vec3(-0.0, -0.0, 42.0),
                    distance = 3.0,
                    duration = 60,
                    weapon = "WEAPON_AIRRIFLE",
                    ammo = 30
                },

                {
                    name = "patoche_gamestand_01",
                    position = vec3(145.554047, 6466.716, 31.35165),
                    rotation = vec3(-0.0, -0.0, -44.0),
                    distance = 3.0,
                    duration = 60,
                    weapon = "WEAPON_AIRRIFLE",
                    ammo = 30
                },

                {
                    name = "patoche_gamestand_02",
                    position = vec3(122.819687, 6410.0874, 30.83457),
                    rotation = vec3(-0.0, 0.0, -50.0),
                    distance = 3.0,
                    duration = 60,
                    weapon = "WEAPON_AIRRIFLE",
                    ammo = 30
                },

                {
                    name = "patoche_gamestand_02",
                    position = vec3(113.418419, 6435.63672, 31.3113823),
                    rotation = vec3(-0.0, 0.0, -44.0),
                    distance = 3.0,
                    duration = 60,
                    weapon = "WEAPON_AIRRIFLE",
                    ammo = 30
                },

                {
                    name = "patoche_gamestand_03",
                    position = vec3(167.814133, 6438.8, 30.3583145),
                    rotation = vec3(-0.0, -0.0, -138.0),
                    distance = 4.0,
                    duration = 40,
                    weapon = "WEAPON_TWBALL",
                    ammo = 10
                },

                {
                    name = "patoche_gamestand_03",
                    position = vec3(138.2807, 6452.974, 30.7697353),
                    rotation = vec3(-0.0, -0.0, -137.0),
                    distance = 4.0,
                    duration = 40,
                    weapon = "WEAPON_TWBALL",
                    ammo = 10
                },

                {
                    name = "patoche_gamestand_trampo",
                    position = vec3(124.768, 6440.581, 32.615),
                    rotation = vec3(0.0, 0.0, 0.0),
                    distance = 4.0,
                    duration = 10
                }
            }
        },
        -- Sandy Placement
        {
            games = {
                {
                    name = 'patoche_gamestand_prop_gym_01',
                    position = vec3(338.2161, 3596.70313, 32.5852165),
                    rotation = vec3(0.000, 0.000, -142.000),
                    difficulty = {
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'medium',
                        'medium',
                        'medium',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'hard',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'medium',
                        'medium',
                        'hard',
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'hard',
                        'medium',
                        'easy',
                        'hard',
                        'hard',
                    },
                    distance = 2.0,
                    duration = 60
                },

                {
                    name = 'patoche_gamestand_prop_gym_01',
                    position = vec3(340.6172, 3598.694, 32.5852165),
                    rotation = vec3(0.0, 0.0, -142.0),
                    difficulty = {
                        'easy',
                        'easy',
                        'medium',
                        'medium',
                        'hard',
                        'hard',
                        'easy',
                        'easy',
                        'easy',
                        { areaSize = 30, speedMultiplier = 1.5 },
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'medium',
                        'hard',
                        'medium',
                        'medium',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'hard',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'medium',
                        'medium',
                        'medium',
                        'hard',
                        'easy',
                        'medium',
                        'easy',
                        'hard',
                        'easy',
                        'hard',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'easy',
                        'hard',
                        'medium',
                        'easy',
                        'hard',
                        'hard',
                    },
                    distance = 2.0,
                    duration = 60
                },

                {
                    name = "patoche_gamestand_01",
                    position = vec3(359.461975, 3566.22, 32.9669533),
                    rotation = vec3(-0.0, -0.0, -90.0),
                    distance = 3.0,
                    duration = 60,
                    weapon = "WEAPON_AIRRIFLE",
                    ammo = 30
                },

                {
                    name = "patoche_gamestand_01",
                    position = vec3(320.81488, 3566.04663, 33.1330376),
                    rotation = vec3(-0.0, -0.0, 92.0),
                    distance = 3.0,
                    duration = 60,
                    weapon = "WEAPON_AIRRIFLE",
                    ammo = 30
                },

                {
                    name = "patoche_gamestand_02",
                    position = vec3(347.68457, 3604.63062, 32.9678268),
                    rotation = vec3(-0.0, 0.0, -147.0),
                    distance = 3.0,
                    duration = 60,
                    weapon = "WEAPON_AIRRIFLE",
                    ammo = 30
                },

                {
                    name = "patoche_gamestand_02",
                    position = vec3(339.339264, 3543.40771, 32.8906364),
                    rotation = vec3(-0.0, 0.0, -7.0),
                    distance = 3.0,
                    duration = 60,
                    weapon = "WEAPON_AIRRIFLE",
                    ammo = 30
                },

                {
                    name = "patoche_gamestand_03",
                    position = vec3(348.908, 3543.67627, 32.38673),
                    rotation = vec3(-0.0, -0.0, -155.0),
                    distance = 4.0,
                    duration = 40,
                    weapon = "WEAPON_TWBALL",
                    ammo = 10
                },

                {
                    name = "patoche_gamestand_trampo",
                    position = vec3(331.257, 3591.120, 34.190),
                    rotation = vec3(0.0, 0.0, 0.0),
                    distance = 4.0,
                    duration = 10
                }
            }
        },
    }
}

