['bountytablet'] = {
  ["name"]        = "bountytablet", 
  ["label"]       = "Bounty Tablet", 
  ["weight"]      = 500, 
  ["type"]        = "item",
  ["image"]       = "bountytablet.png", 
  ["unique"]      = true,
  ["useable"]     = true,
  ["shouldClose"] = true,
  ["combinable"]  = nil,
  ["description"] = "A tablet used by bounty hunters to see current contracts for their office",
},