Labels = {
  ['ENG'] = {
    Target = {
      BuyTablet        = "Buy Tablet",
      TakeTest         = "Take License Test",
      CreateBounty     = "Create Bounty",
      ReturnBounty     = "Return Bounty",
      CollectReward    = "Collect Rewards",
      RetrieveVehicles = "Retrieve Seized Vehicles",
      BossMenu         = "Boss Menu",
    },

    SeizedVehicles      = "The following vehicles have been seized from you: %s",
    NoBountiesHere      = "This person is not wanted by this office",
    ReturnedBounty      = "You have returned a bounty for $%s",
    FinedForBounty      = "You have been fined $%s for having a bounty",
    JailedForBounty     = "You have been jailed for %s minutes for having a bounty",
    PlayerShouldBeDead  = "The player you are trying to return a bounty for must be dead",
    NooneNearby         = "There is no one nearby to you to return",
    BountyCreated       = "A bounty has been created at the %s Office for %s with a reward of $%s",
    NoEarnings          = "You have no earnings to collect from this office",
    CollectedEarnings   = "You have collected $%s in earnings from this office",
    BountyCompleted     = "You have completed %s bounties by killing this person earning yourself $%s",
    CollectOffice       = "You will need to go to the %s office to collect your reward",
    RequiresJob         = "You don't have the correct job for this.",
    RequiresItem        = "You are not carrying the correct item for this.",
    RequiresLicense     = "You have not passed the correct license test for this.",
    NotEnoughMoney      = "You don't have enough money for this.",
    NoSeizedVehicles    = "You have no seized vehicles to retrieve",
    ReleasedVehicles    = "You have released %s vehicles from the impound",
    Months              = "Months",


    --## WEBHOOK SETTINGS
    BountyIncreased     = "Bounty Increased",
    BountyCreated       = "Bounty Created",
    BountyComplete      = "Bounty Returned",
    Name                = "Name",
    Price               = "Price",
    Description         = "DESCRIPTION",
    Reason              = "REASON",
    Consequences        = "CONSEQUENCES",

    FineAmount          = "Fine Amount",
    JailTime            = "Jail Time",
    VehiclesSeized      = "Vehicles Seized",
  },  
  ['FRA'] = {
    Target = {
      BuyTablet        = "Acheter une Tablette",
      TakeTest         = "Passer l'Examen de Permis",
      CreateBounty     = "Créer une Prime",
      ReturnBounty     = "Rendre la Prime",
      CollectReward    = "Collecter les Récompenses",
      RetrieveVehicles = "Récupérer les Véhicules Saisis",
      BossMenu         = "Menu du Patron",
    },
    SeizedVehicles      = "Les véhicules suivants ont été saisis de votre part : %s",
    NoBountiesHere      = "Cette personne n'est pas recherchée par ce bureau",
    ReturnedBounty      = "Vous avez rendu une prime de %s",
    FinedForBounty      = "Vous avez été condamné à une amende de %s pour avoir une prime",
    JailedForBounty     = "Vous avez été emprisonné pendant %s minutes pour avoir une prime",
    PlayerShouldBeDead  = "Le joueur pour lequel vous essayez de rendre une prime doit être mort",
    NooneNearby         = "Il n'y a personne à proximité pour rendre",
    BountyCreated       = "Une prime a été créée au bureau de %s pour %s avec une récompense de %s",
    NoEarnings          = "Vous n'avez pas de gains à collecter dans ce bureau",
    CollectedEarnings   = "Vous avez collecté %s en gains de ce bureau",
    BountyCompleted     = "Vous avez complété %s primes en tuant cette personne, vous gagnerez %s",
    CollectOffice       = "Vous devrez vous rendre au bureau de %s pour collecter votre récompense",
    RequiresJob         = "Vous n'avez pas le bon emploi pour ceci.",
    RequiresItem        = "Vous ne transportez pas l'objet correct pour ceci.",
    RequiresLicense     = "Vous n'avez pas réussi l'examen de permis correct pour ceci.",
    NotEnoughMoney      = "Vous n'avez pas assez d'argent pour ceci.",
    NoSeizedVehicles    = "Vous n'avez pas de véhicules saisis à récupérer",
    ReleasedVehicles    = "Vous avez libéré %s véhicules de la fourrière",
    Months              = "Mois",
    
    -- WEBHOOK SETTINGS
    BountyIncreased     = "Prime augmentée",
    BountyCreated       = "Prime créée",
    BountyComplete      = "Prime rendue",
    Name                = "Nom",
    Price               = "Prix",
    Description         = "DESCRIPTION",
    Reason              = "RAISON",
    Consequences        = "CONSÉQUENCES",
    FineAmount          = "Montant de l'amende",
    JailTime            = "Temps d'emprisonnement",
    VehiclesSeized      = "Véhicules saisis", 
  },
  ['ESP'] = {
    Target = {
      BuyTablet        = "Comprar Tableta",
      TakeTest         = "Realizar Prueba de Licencia",
      CreateBounty     = "Crear Recompensa",
      ReturnBounty     = "Devolver Recompensa",
      CollectReward    = "Recoger Recompensas",
      RetrieveVehicles = "Recuperar Vehículos Decomisados",
      BossMenu         = "Menú del Jefe",
    },
    SeizedVehicles      = "Los siguientes vehículos te han sido decomisados: %s",
    NoBountiesHere      = "Esta persona no está buscada por esta oficina",
    ReturnedBounty      = "Has devuelto una recompensa por %s",
    FinedForBounty      = "Has sido multado con %s por tener una recompensa",
    JailedForBounty     = "Has sido encarcelado durante %s minutos por tener una recompensa",
    PlayerShouldBeDead  = "El jugador por el que estás intentando devolver una recompensa debe estar muerto",
    NooneNearby         = "No hay nadie cerca de ti para devolver",
    BountyCreated       = "Se ha creado una recompensa en la Oficina de %s por %s con una recompensa de %s",
    NoEarnings          = "No tienes ganancias para recoger en esta oficina",
    CollectedEarnings   = "Has recogido %s en ganancias de esta oficina",
    BountyCompleted     = "Has completado %s recompensas al matar a esta persona, ganando %s",
    CollectOffice       = "Necesitarás ir a la oficina de %s para recoger tu recompensa",
    RequiresJob         = "No tienes el trabajo correcto para esto.",
    RequiresItem        = "No llevas el objeto correcto para esto.",
    RequiresLicense     = "No has aprobado el examen de licencia correcto para esto.",
    NotEnoughMoney      = "No tienes suficiente dinero para esto.",
    NoSeizedVehicles    = "No tienes vehículos decomisados para recuperar",
    ReleasedVehicles    = "Has liberado %s vehículos del depósito",
    Months              = "Meses",
    
    -- WEBHOOK SETTINGS
    BountyIncreased     = "Recompensa aumentada",
    BountyCreated       = "Recompensa creada",
    BountyComplete      = "Recompensa devuelta",
    Name                = "Nombre",
    Price               = "Precio",
    Description         = "DESCRIPCIÓN",
    Reason              = "RAZÓN",
    Consequences        = "CONSECUENCIAS",
    FineAmount          = "Monto de la multa",
    JailTime            = "Tiempo de encarcelamiento",
    VehiclesSeized      = "Vehículos decomisados",
  }, 
  ['NLD'] = {
    Target = {
      BuyTablet        = "Tablet Kopen",
      TakeTest         = "Rijbewijs Testen",
      CreateBounty     = "Premie Uitvaardigen",
      ReturnBounty     = "Premie Teruggeven",
      CollectReward    = "Beloningen Innen",
      RetrieveVehicles = "Inbeslaggenomen Voertuigen Terughalen",
      BossMenu         = "Baas Menu",
    },
    SeizedVehicles      = "De volgende voertuigen zijn van jou in beslag genomen: %s",
    NoBountiesHere      = "Deze persoon wordt niet gezocht door dit kantoor",
    ReturnedBounty      = "Je hebt een premie ter waarde van %s teruggegeven",
    FinedForBounty      = "Je hebt een boete van %s gekregen voor het hebben van een premie",
    JailedForBounty     = "Je zit %s minuten vast omdat je een premie hebt",
    PlayerShouldBeDead  = "De speler voor wie je een premie wilt teruggeven, moet dood zijn",
    NooneNearby         = "Er is niemand in de buurt om aan terug te geven",
    BountyCreated       = "Er is een premie uitgevaardigd op het kantoor van %s voor %s met een beloning van %s",
    NoEarnings          = "Je hebt geen inkomsten om te innen van dit kantoor",
    CollectedEarnings   = "Je hebt $%s aan inkomsten van dit kantoor ontvangen",
    BountyCompleted     = "Je hebt %s premies voltooid door deze persoon te doden, wat je $%s heeft opgeleverd",
    CollectOffice       = "Je moet naar het kantoor van %s gaan om je beloning op te halen",
    RequiresJob         = "Je hebt niet de juiste baan hiervoor.",
    RequiresItem        = "Je draagt niet het juiste item hiervoor.",
    RequiresLicense     = "Je hebt niet het juiste rijbewijs hiervoor gehaald.",
    NotEnoughMoney      = "Je hebt hier niet genoeg geld voor.",
    NoSeizedVehicles    = "Je hebt geen in beslag genomen voertuigen om terug te halen",
    ReleasedVehicles    = "Je hebt %s voertuigen vrijgegeven uit de impound",
    Months              = "Maanden",
    
    -- WEBHOOK SETTINGS
    BountyIncreased     = "Premie Verhoogd",
    BountyCreated       = "Premie Uitgevaardigd",
    BountyComplete      = "Premie Teruggegeven",
    Name                = "Naam",
    Price               = "Prijs",
    Description         = "BESCHRIJVING",
    Reason              = "REDEN",
    Consequences        = "GEVOLGEN",
    FineAmount          = "Boetebedrag",
    JailTime            = "Gevangenisstraf",
    VehiclesSeized      = "Voertuigen Inbeslaggenomen",    
  },
  ['DAN'] = {
    Target = {
      BuyTablet        = "Køb Tablet",
      TakeTest         = "Tag Køreprøve",
      CreateBounty     = "Opret Jagt",
      ReturnBounty     = "Aflever Jagt",
      CollectReward    = "Indkassér Belønninger",
      RetrieveVehicles = "Hent Beslaglagte Køretøjer",
      BossMenu         = "Chef Menu",
    },
    SeizedVehicles      = "Følgende køretøjer er blevet beslaglagt fra dig: %s",
    NoBountiesHere      = "Denne person er ikke eftersøgt af dette kontor",
    ReturnedBounty      = "Du har afleveret en jagt for %s",
    FinedForBounty      = "Du har fået en bøde på %s for at have en jagt",
    JailedForBounty     = "Du er blevet fængslet i %s minutter for at have en jagt",
    PlayerShouldBeDead  = "Spilleren, du forsøger at aflevere en jagt for, skal være død",
    NooneNearby         = "Der er ingen i nærheden af dig at aflevere til",
    BountyCreated       = "Der er oprettet en jagt på %s kontor for %s med en belønning på %s",
    NoEarnings          = "Du har ingen indtjening at indkassere fra dette kontor",
    CollectedEarnings   = "Du har indkasseret %s i indtjening fra dette kontor",
    BountyCompleted     = "Du har fuldført %s jagter ved at dræbe denne person og tjent dig selv %s",
    CollectOffice       = "Du skal gå til %s kontor for at indkassere din belønning",
    RequiresJob         = "Du har ikke det korrekte job til dette.",
    RequiresItem        = "Du bærer ikke det korrekte emne til dette.",
    RequiresLicense     = "Du har ikke bestået den korrekte køreprøve til dette.",
    NotEnoughMoney      = "Du har ikke nok penge til dette.",
    NoSeizedVehicles    = "Du har ingen beslaglagte køretøjer at hente",
    ReleasedVehicles    = "Du har frigivet %s køretøjer fra impound",
    Months              = "Måneder",
    
    -- WEBHOOK SETTINGS
    BountyIncreased     = "Jagten er øget",
    BountyCreated       = "Jagten er oprettet",
    BountyComplete      = "Jagten er afleveret",
    Name                = "Navn",
    Price               = "Pris",
    Description         = "BESKRIVELSE",
    Reason              = "ÅRSAG",
    Consequences        = "KONSEKVENSER",
    FineAmount          = "Bødebeløb",
    JailTime            = "Fængselstid",
    VehiclesSeized      = "Køretøjer Beslaglagt",    
  },
  ['SWE'] = {
    Target = {
      BuyTablet        = "Köp Tablet",
      TakeTest         = "Gör Körkortsprov",
      CreateBounty     = "Skapa Jakt",
      ReturnBounty     = "Lämna In Jakt",
      CollectReward    = "Inkassera Belöningar",
      RetrieveVehicles = "Hämta Beslagtagna Fordon",
      BossMenu         = "Boss Meny",
    },
    SeizedVehicles      = "Följande fordon har beslagtagits från dig: %s",
    NoBountiesHere      = "Denna person är inte efterlyst av detta kontor",
    ReturnedBounty      = "Du har lämnat in en jakt för %s",
    FinedForBounty      = "Du har fått en böter på %s för att ha en jakt",
    JailedForBounty     = "Du har blivit fängslad i %s minuter för att ha en jakt",
    PlayerShouldBeDead  = "Spelaren du försöker lämna in en jakt för måste vara död",
    NooneNearby         = "Det finns ingen i närheten av dig att lämna in till",
    BountyCreated       = "En jakt har skapats på %s kontor för %s med en belöning på %s",
    NoEarnings          = "Du har ingen intjäning att inkassera från detta kontor",
    CollectedEarnings   = "Du har inkasserat %s i intjäning från detta kontor",
    BountyCompleted     = "Du har slutfört %s jakter genom att döda denna person och tjänat %s",
    CollectOffice       = "Du måste gå till %s kontor för att inkassera din belöning",
    RequiresJob         = "Du har inte rätt jobb för detta.",
    RequiresItem        = "Du har inte rätt föremål för detta.",
    RequiresLicense     = "Du har inte klarat rätt körkortsprov för detta.",
    NotEnoughMoney      = "Du har inte tillräckligt med pengar för detta.",
    NoSeizedVehicles    = "Du har inga beslagtagna fordon att hämta",
    ReleasedVehicles    = "Du har frigivit %s fordon från impound",
    Months              = "Månader",
    
    -- WEBHOOK SETTINGS
    BountyIncreased     = "Jakten ökade",
    BountyCreated       = "Jakten skapades",
    BountyComplete      = "Jakten lämnades in",
    Name                = "Namn",
    Price               = "Pris",
    Description         = "BESKRIVNING",
    Reason              = "ORSAK",
    Consequences        = "KONSEKVENSER",
    FineAmount          = "Bötesbelopp",
    JailTime            = "Fängelsetid",
    VehiclesSeized      = "Fordon Beslagtagna",    
  },
  ['DEU'] = {
    Target = {
      BuyTablet        = "Tablet Kaufen",
      TakeTest         = "Führerscheinprüfung Ablegen",
      CreateBounty     = "Jagd Erstellen",
      ReturnBounty     = "Jagd Zurückgeben",
      CollectReward    = "Belohnungen Einsammeln",
      RetrieveVehicles = "Beschlagnahmte Fahrzeuge Abholen",
      BossMenu         = "Boss Menü",
    },
    SeizedVehicles      = "Die folgenden Fahrzeuge wurden von Ihnen beschlagnahmt: %s",
    NoBountiesHere      = "Diese Person wird von diesem Büro nicht gesucht",
    ReturnedBounty      = "Sie haben eine Jagd im Wert von %s zurückgegeben",
    FinedForBounty      = "Sie wurden mit %s bestraft, weil Sie eine Jagd hatten",
    JailedForBounty     = "Sie wurden für %s Minuten ins Gefängnis gesteckt, weil Sie eine Jagd hatten",
    PlayerShouldBeDead  = "Der Spieler, für den Sie eine Jagd zurückgeben möchten, muss tot sein",
    NooneNearby         = "Es ist niemand in Ihrer Nähe, dem Sie etwas zurückgeben könnten",
    BountyCreated       = "Es wurde eine Jagd im %s Büro für %s mit einer Belohnung von %s erstellt",
    NoEarnings          = "Sie haben keine Einnahmen, die Sie von diesem Büro einsammeln könnten",
    CollectedEarnings   = "Sie haben %s an Einnahmen von diesem Büro eingesammelt",
    BountyCompleted     = "Sie haben %s Jagden abgeschlossen, indem Sie diese Person getötet haben, und %s verdient",
    CollectOffice       = "Sie müssen zum %s Büro gehen, um Ihre Belohnung einzusammeln",
    RequiresJob         = "Sie haben nicht den richtigen Job dafür.",
    RequiresItem        = "Sie tragen nicht den richtigen Gegenstand dafür.",
    RequiresLicense     = "Sie haben die richtige Führerscheinprüfung dafür nicht bestanden.",
    NotEnoughMoney      = "Sie haben nicht genug Geld dafür.",
    NoSeizedVehicles    = "Sie haben keine beschlagnahmten Fahrzeuge zum Abholen",
    ReleasedVehicles    = "Sie haben %s Fahrzeuge aus der Pfund freigegeben",
    Months              = "Monate",
    
    -- WEBHOOK SETTINGS
    BountyIncreased     = "Jagd erhöht",
    BountyCreated       = "Jagd erstellt",
    BountyComplete      = "Jagd zurückgegeben",
    Name                = "Name",
    Price               = "Preis",
    Description         = "BESCHREIBUNG",
    Reason              = "GRUND",
    Consequences        = "KONSEQUENZEN",
    FineAmount          = "Strafsumme",
    JailTime            = "Gefängniszeit",
    VehiclesSeized      = "Fahrzeuge Beschlagnahmt",    
  },  
  ['ARA'] = {
    Target = {
      BuyTablet        = "شراء الجهاز اللوحي",
      TakeTest         = "إجتياز اختبار الترخيص",
      CreateBounty     = "إنشاء مكافأة",
      ReturnBounty     = "إرجاع المكافأة",
      CollectReward    = "جمع المكافآت",
      RetrieveVehicles = "استرجاع المركبات المصادرة",
      BossMenu         = "قائمة الزعيم",
    },
    SeizedVehicles      = "تمت مصادرة المركبات التالية منك: %s",
    NoBountiesHere      = "هذا الشخص لا يتم مطاردته من هذا المكتب",
    ReturnedBounty      = "لقد قمت بإرجاع مكافأة بقيمة %s",
    FinedForBounty      = "لقد تم تغريمك بمبلغ %s لامتلاك مكافأة",
    JailedForBounty     = "تم سجنك لمدة %s دقيقة لامتلاك مكافأة",
    PlayerShouldBeDead  = "اللاعب الذي تحاول إرجاع مكافأة له يجب أن يكون ميتًا",
    NooneNearby         = "لا يوجد أحد بالقرب منك لترجيع المكافأة إليه",
    BountyCreated       = "تم إنشاء مكافأة في مكتب %s لـ %s بمكافأة قدرها %s",
    NoEarnings          = "ليس لديك أي أرباح لتجميعها من هذا المكتب",
    CollectedEarnings   = "لقد جمعت %s في الأرباح من هذا المكتب",
    BountyCompleted     = "لقد أكملت %s مكافآت عن طريق قتل هذا الشخص وكسب %s",
    CollectOffice       = "ستحتاج للذهاب إلى مكتب %s لجمع مكافأتك",
    RequiresJob         = "ليس لديك الوظيفة الصحيحة لهذا.",
    RequiresItem        = "أنت لا تحمل العنصر الصحيح لهذا.",
    RequiresLicense     = "لم تجتاز الاختبار الصحيح لهذا الترخيص.",
    NotEnoughMoney      = "ليس لديك ما يكفي من المال لهذا.",
    NoSeizedVehicles    = "ليس لديك مركبات مصادرة لاسترجاعها",
    ReleasedVehicles    = "لقد أفرجت عن %s مركبات من مكان الحجز",
    Months              = "أشهر",
    
    -- WEBHOOK SETTINGS
    BountyIncreased     = "تم زيادة المكافأة",
    BountyCreated       = "تم إنشاء المكافأة",
    BountyComplete      = "تم إرجاع المكافأة",
    Name                = "الاسم",
    Price               = "السعر",
    Description         = "الوصف",
    Reason              = "السبب",
    Consequences        = "العواقب",
    FineAmount          = "مبلغ الغرامة",
    JailTime            = "وقت السجن",
    VehiclesSeized      = "تم مصادرة المركبات",    
  },
  ['HIN'] = {
    Target = {
      BuyTablet        = "टैबलेट खरीदें",
      TakeTest         = "लाइसेंस परीक्षण दें",
      CreateBounty     = "मुआवजा बनाएं",
      ReturnBounty     = "मुआवजा वापस करें",
      CollectReward    = "सवारी इनाम लें",
      RetrieveVehicles = "मुकदमी से जब्त की गई गाड़ियों को पुनः प्राप्त करें",
      BossMenu         = "मालिक मेनू",
    },
    SeizedVehicles      = "निम्नलिखित गाड़ियाँ आपसे जब्त की गई हैं: %s",
    NoBountiesHere      = "यह व्यक्ति इस कार्यालय द्वारा खोजा नहीं जाता",
    ReturnedBounty      = "आपने %s के लिए एक मुआवजा वापस किया है",
    FinedForBounty      = "आपको %s के लिए जुर्माना लगाया गया है क्योंकि आपके पास एक मुआवजा है",
    JailedForBounty     = "आपको %s मिनटों के लिए जेल में बंद कर दिया गया है क्योंकि आपके पास एक मुआवजा है",
    PlayerShouldBeDead  = "वह खिलाड़ी, जिसके लिए आप मुआवजा वापस करने का प्रयास कर रहे हैं, की तो मरा हुआ होना चाहिए",
    NooneNearby         = "आपके पास किसी को मुआवजा वापस करने के लिए नहीं है",
    BountyCreated       = "एक मुआवजा %s कार्यालय में %s के लिए एक पुरस्कार के साथ बनाया गया है",
    NoEarnings          = "आपके पास इस कार्यालय से इनाम लेने के लिए कोई कमाई नहीं है",
    CollectedEarnings   = "आपने इस कार्यालय से %s की कमाई इनाम लिया है",
    BountyCompleted     = "आपने इस व्यक्ति को मारकर %s मुआवजाओं को पूरा किया है, जिससे आपको %s कमाई हुई है",
    CollectOffice       = "आपको अपना पुरस्कार प्राप्त करने के लिए %s कार्यालय जाने की आवश्यकता होगी",
    RequiresJob         = "आपके पास इसके लिए सही नौकरी नहीं है।",
    RequiresItem        = "आप इसके लिए सही आइटम नहीं ले रहे हैं।",
    RequiresLicense     = "आपने इसके लिए सही लाइसेंस परीक्षा नहीं पास की है।",
    NotEnoughMoney      = "आपके पास इसके लिए पर्याप्त पैसे नहीं हैं।",
    NoSeizedVehicles    = "आपके पास पुनर्हस्तकृत गाड़ियाँ नहीं हैं",
    ReleasedVehicles    = "आपने अदालत से %s गाड़ियाँ मुकदमा से छोड़ दी हैं",
    Months              = "महीने",
    
    -- WEBHOOK SETTINGS
    BountyIncreased     = "मुआवजा बढ़ गया",
    BountyCreated       = "मुआवजा बनाया गया",
    BountyComplete      = "मुआवजा वापस किया गया",
    Name                = "नाम",
    Price               = "मूल्य",
    Description         = "विवरण",
    Reason              = "कारण",
    Consequences        = "परिणाम",
    FineAmount          = "जुर्माना राशि",
    JailTime            = "कारागार का समय",
    VehiclesSeized      = "गाड़ियाँ जब्त की गईं",    
  },
  ['POR'] = {
    Target = {
      BuyTablet        = "Comprar Tablet",
      TakeTest         = "Realizar Teste de Licença",
      CreateBounty     = "Criar Recompensa",
      ReturnBounty     = "Devolver Recompensa",
      CollectReward    = "Recolher Recompensas",
      RetrieveVehicles = "Recuperar Veículos Apreendidos",
      BossMenu         = "Menu do Chefe",
    },
    SeizedVehicles      = "Os seguintes veículos foram apreendidos de você: %s",
    NoBountiesHere      = "Esta pessoa não está procurada por este escritório",
    ReturnedBounty      = "Você devolveu uma recompensa de %s",
    FinedForBounty      = "Você foi multado em %s por ter uma recompensa",
    JailedForBounty     = "Você foi preso por %s minutos por ter uma recompensa",
    PlayerShouldBeDead  = "O jogador para o qual você está tentando devolver uma recompensa deve estar morto",
    NooneNearby         = "Não há ninguém próximo a você para devolver",
    BountyCreated       = "Uma recompensa foi criada no escritório %s para %s com uma recompensa de %s",
    NoEarnings          = "Você não tem ganhos para recolher deste escritório",
    CollectedEarnings   = "Você recolheu %s em ganhos deste escritório",
    BountyCompleted     = "Você completou %s recompensas matando esta pessoa, ganhando %s para você mesmo",
    CollectOffice       = "Você precisará ir ao escritório %s para recolher sua recompensa",
    RequiresJob         = "Você não tem o emprego correto para isso.",
    RequiresItem        = "Você não está carregando o item correto para isso.",
    RequiresLicense     = "Você não passou no teste de licença correto para isso.",
    NotEnoughMoney      = "Você não tem dinheiro suficiente para isso.",
    NoSeizedVehicles    = "Você não tem veículos apreendidos para recuperar",
    ReleasedVehicles    = "Você liberou %s veículos do depósito",
    Months              = "Meses",
    
    -- WEBHOOK SETTINGS
    BountyIncreased     = "Recompensa Aumentada",
    BountyCreated       = "Recompensa Criada",
    BountyComplete      = "Recompensa Devolvida",
    Name                = "Nome",
    Price               = "Preço",
    Description         = "DESCRIÇÃO",
    Reason              = "RAZÃO",
    Consequences        = "CONSEQUÊNCIAS",
    FineAmount          = "Valor da Multa",
    JailTime            = "Tempo de Prisão",
    VehiclesSeized      = "Veículos Apreendidos",    
  },
}
